// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Area is the predicate function for area builders.
type Area func(*sql.Selector)

// Disease is the predicate function for disease builders.
type Disease func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Level is the predicate function for level builders.
type Level func(*sql.Selector)

// Statistic is the predicate function for statistic builders.
type Statistic func(*sql.Selector)
